import { Sprite } from '../scripts/rendering';

export const spritesheet: Sprite[] = [
	{
		name: 'exit',
		path: 'src/assets/sprites/staircase.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'entrance',
		path: 'src/assets/sprites/trapdoor.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'hoarder',
		path: 'src/assets/sprites/hoarder.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'bookcase',
		path: 'src/assets/sprites/bookcase.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'bookcase-low',
		path: 'src/assets/sprites/bookcase-low.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'bookcase-low-decorated',
		path: 'src/assets/sprites/bookcase-low-decorated.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'table',
		path: 'src/assets/sprites/table.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'skeleton',
		path: 'src/assets/sprites/skeleton.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'skulls',
		path: 'src/assets/sprites/skulls.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'witchhat',
		path: 'src/assets/sprites/witchhat.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'frog',
		path: 'src/assets/sprites/frog.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'hornet-box',
		path: 'src/assets/sprites/hornet-box.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'hornet',
		path: 'src/assets/sprites/hornet.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'full-friendly-health',
		path: 'src/assets/sprites/health3.png',
		size: { width: 4, height: 3 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'full-enemy-health',
		path: 'src/assets/sprites/health3.png',
		size: { width: 4, height: 3 },
		origin: { x: 3, y: 0 },
	},
	{
		name: 'empty-health',
		path: 'src/assets/sprites/health3.png',
		size: { width: 4, height: 3 },
		origin: { x: 6, y: 0 },
	},
	{
		name: 'single-coin',
		path: 'src/assets/sprites/coins.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'two-coins',
		path: 'src/assets/sprites/coins.png',
		size: { width: 16, height: 16 },
		origin: { x: 16, y: 0 },
	},
	{
		name: 'three-coins',
		path: 'src/assets/sprites/coins.png',
		size: { width: 16, height: 16 },
		origin: { x: 32, y: 0 },
	},
	{
		name: 'four-coins',
		path: 'src/assets/sprites/coins.png',
		size: { width: 16, height: 16 },
		origin: { x: 48, y: 0 },
	},
	{
		name: 'gochapon-machine',
		path: 'src/assets/sprites/gochapon.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'gochapon-egg-1',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 0, y: 0 },
	},
	{
		name: 'gochapon-egg-2',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 16, y: 0 },
	},
	{
		name: 'gochapon-egg-3',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 32, y: 0 },
	},
	{
		name: 'gochapon-egg-4',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 48, y: 0 },
	},
	{
		name: 'gochapon-egg-5',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 64, y: 0 },
	},
	{
		name: 'gochapon-egg-6',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 80, y: 0 },
	},
	{
		name: 'gochapon-egg-6',
		path: 'src/assets/sprites/gochapon-egg.png',
		size: { width: 16, height: 16 },
		origin: { x: 96, y: 0 },
	},
]
